# Generated by Django 3.0.2 on 2020-02-02 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GenParams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('param_name', models.CharField(default=None, max_length=200)),
                ('value', models.CharField(default=None, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='plant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(choices=[('Zinnia', 'zinnia'), ('Tomate', 'tomate'), ('TomatePM', 'tomate PM'), ('Capucine', 'capucine'), ('Autre', 'autre')], default='Autre', max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='pots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pot_id', models.CharField(default='$', max_length=30)),
                ('note', models.CharField(default='$', max_length=200)),
                ('diametre', models.IntegerField(default=0)),
                ('hauteur', models.IntegerField(default=0)),
                ('longueur', models.IntegerField(default=0)),
                ('largeur', models.IntegerField(default=0)),
            ],
        ),
    ]
