# Generated by Django 3.0.2 on 2020-02-02 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plant',
            old_name='Type',
            new_name='type',
        ),
    ]
