# Generated by Django 3.0.2 on 2020-02-03 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0005_plant_potid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='PotId',
        ),
    ]
