# Generated by Django 3.0.2 on 2020-01-21 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0003_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='pub_date',
        ),
    ]
