# Generated by Django 3.0.2 on 2020-01-21 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0004_remove_question_pub_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
    ]
