# Generated by Django 3.0.2 on 2020-01-23 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0007_auto_20200121_2004'),
    ]

    operations = [
        migrations.CreateModel(
            name='pots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pot_id', models.CharField(default=None, max_length=200)),
            ],
        ),
    ]
