# Generated by Django 3.0.2 on 2020-01-23 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0008_pots'),
    ]

    operations = [
        migrations.AddField(
            model_name='pots',
            name='diametre',
            field=models.IntegerField(default=0),
        ),
    ]
