# Generated by Django 3.0.2 on 2020-01-23 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0010_auto_20200123_1930'),
    ]

    operations = [
        migrations.CreateModel(
            name='espece',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especes', models.CharField(choices=[('Zinnia', 'zinnia'), ('Tomate', 'tomate'), ('TomatePM', 'tomate PM'), ('Capucine', 'capucine'), ('Autre', 'autre')], default='Autre', max_length=9)),
            ],
        ),
    ]
