# Generated by Django 3.0.2 on 2020-01-23 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0011_espece'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pots',
            name='note',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='pots',
            name='pot_id',
            field=models.CharField(max_length=30),
        ),
    ]
