# Generated by Django 3.0.2 on 2020-01-24 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0012_auto_20200123_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pots',
            name='note',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AlterField(
            model_name='pots',
            name='pot_id',
            field=models.CharField(default=' ', max_length=30),
        ),
    ]
