# Generated by Django 3.0.2 on 2020-02-02 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0015_auto_20200202_1913'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plant',
            old_name='plant',
            new_name='type',
        ),
    ]
