# Generated by Django 3.0.2 on 2020-02-02 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0016_auto_20200202_1919'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plant',
            old_name='type',
            new_name='Type',
        ),
    ]
