# Generated by Django 3.0.2 on 2020-02-02 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0019_auto_20200202_1946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='PlId',
        ),
    ]
